services:
  rabbitmq-deployment:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - localnet

  mockeventgenerator:
    image: mockeventgenerator:latest
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=rabbitmq-deployment
    depends_on:
      - rabbitmq-deployment
    networks:
      - localnet

  leaderboard:
    image: leaderboard:latest
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=rabbitmq-deployment
    depends_on:
      - mockeventgenerator
    ports:
      - "8080:8080"
    networks:
      - localnet
    volumes:
      - db_data:/db

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8081"
    networks:
      - localnet

volumes:
  db_data:

networks:
  localnet:
    driver: bridge