apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockeventgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockeventgenerator
  template:
    metadata:
      labels:
        app: mockeventgenerator
    spec:
      containers:
      - name: mockeventgenerator
        imagePullPolicy: Never
        image: mockeventgenerator:latest
        env:
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_HOST
          value: "rabbitmq"

